models:
  Qwen2.5-VL:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Qwen2.5-VL-7B-Instruct"
  LLaVA-Next:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/llava-v1.6-mistral-7b-hf/"
  Molmo-D:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Molmo-7B-D-0924/"
  DeepSeek-VL2:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/deepseek-vl2-tiny/"
  InternVL3:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/InternVL3-8B/"
  LLaMA-3:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Llama-3.2-11B-Vision-Instruct/"
  Phi-4:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Phi-4-multimodal-instruct/"
  Gemma-3:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/gemma-3-4b-it/"
  Pixtral:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Pixtral-12B-2409"
  Ovis-2:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Ovis2-8B/"
  Mulberry:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Mulberry_qwen2vl_7b/"
  R1-Onevision:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/R1-Onevision-7B/"
  Visionary-R1:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Visionary-R1/"
  LLaVA-CoT:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Llama-3.2V-11B-cot/"
  R1-VL:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/R1-VL-7B/"
  Insight-V:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/Insight-V-Reason-LLaMA3/"
  Cambrian:
    params:
      model_name_or_path: "/mnt/data2/bingkui/model_zoo/cambrian-8b/"


# dataset config
dataset: "/mnt/data2/bingkui/MCHA_experiments/dataset"
